privacy_policy_1 = """
1.1 This Privacy Policy sets out how we, Crypto Recovery, collect, use, store, transfer and protect your personal data that you provide to us or
that are otherwise receive by or automatically generated by us in connection with your use of our Internet platform (website). For the purposes of this Privacy Policy, "we", "us" and "our" refer to the limited
liability company "DUST FOUNDATION", and "you", "your" refer to you, the users of our platform and its services. 

1.2. Terms of use of the Crypto Recovery Internet platform. This Privacy Policy which is available at https://cryptorecover.com/ is an integral part of our User agreement, which should be set out the conditions under which you can use our
services, and is considered only in conjunction with the abovementioned User agreement.

1.3. Privacy principles. Crypto Recovery adheres to the following principles of personal data collection and processing:
* We do not use your data to display advertisements.
* We store only the data necessary for Crypto Recovery to operate as a secure and multi-functional educational platform in the cryptocurrency domain. 
"""

privacy_policy_2 = """
2.1 Legal basis for the processing of personal data is your consent to the processing of personal data, Regulation of the European Parliament and of the Council (EU) 2016/679
on the protection of individuals with regard to the processing of personal data and on the free movement of such data, and on the repeal of Directive 95/46 /EU (General Data Protection Regulation) https://gdpr.algolia.com/

2.2. Processing of personal data is carried out for specific and legal purposes, determined with the consent of the subject of personal data, or in cases provided for by law, in the manner specified by it. 

2.3. Basis for processing personal data are:
* consent of the subject of personal data to processing of his personal data;
* permission to process personal data granted to the owner of personal data in accordance with the law exclusively for the exercise of his powers;
* conclusion and execution of a transaction to which the subject of personal data is a party or which was concluded for the benefit of the subject of personal data or for the implementation of measures preceding the conclusion of the transaction at the request of the subject of personal data;
* protection of vital interests of the subject of personal data;
* the need to fulfill the obligation of the owner of personal data, which is provided by law;
* the need to protect the legitimate interests of the owner of personal data or a third party to whom personal data is transferred, except in cases where the needs to protect the fundamental rights and freedoms of the subject of personal data in connection with the processing of his data prevail over such interests. 

2.4. We process your personal data only to the extent necessary to provide effective and innovative services to our users, as well as to detect, prevent or otherwise solve fraud or
security problems, primarily taking care of your interests and protecting your fundamental rights and freedoms that require protection of personal data. 
"""

privacy_policy_3 = """
3.1. Basic account information. When registering on the Crypto Recovery platform, you use your profiles created in Telegram. At the time of registration, the platform receives the following data from the user: 
* e-mail;
* nickname (user name);
* ID and nickname from Telegram;

3.2. The user specifies his name at his own discretion. We do not verify its authenticity. The name is used to make it easier for us, your contacts, and other people to contact you. 

3.3. Email address will only be used to send you messages related to your use of the resources and services of the platform, for example, a password recovery code if you forget it. You will not receive any marketing messages. 

3.4. We use Telegram for communication between platform members.Telegram are cloud services. Messages, photos, videos, and documents from cloud chats are stored on Telegram servers in accordance with their privacy policies and user rules

3.5. Crypto Recovery collects only those personal data that are consciously and voluntarily provided by you as a subject of personal data for the purpose of using the services
of the platform, on the basis of the consent to the processing of personal data obtained during the registration, which in accordance with the requirements of the law is the
consent of the subject of personal data to their personal data processing, in accordance with the purpose of processing formulated in this Policy. When visiting the platform and using its services, all logins to the system may be recorded. Other user traffic information is not processed or stored. We do not collect any information that is required by law to be processed, such as information about racial or ethnic origin, political, religious, or ideological beliefs, membership in political parties and trade unions, criminal convictions for a crime or criminal convictions, as well as data related to health, sexual life, biometric or genetic data. We may collect data about statistics of visits to the Site. The information may contain information about the connection, traffic, the user's browser, as well as information about the date, time, time spent on the Internet, and time spent on the Site. 
"""

privacy_policy_5 = """
4.1. Our services. We will process your data to ensure your comfortable and safe use of Crypto Recovery services and products. The processing and storage of the provided personal data is carried out in data centers where the equipment that ensures the functioning of the site's services is located. 
The provided personal data is processed and may be stored in the personal database or a separate table of the platform database. 

4.2. Protection of personal data. In compliance with the legislation on the protection of personal data (including international legislation - GDPR) our web platform guarantees its security. Dissemination of personal data without the consent of the subject of personal data or a person authorized by him is allowed in cases defined by law and only (if necessary) in the interests of national security, 
economic well-being, and human rights. 

4.3. Advanced features. We may use some aggregated data about the way you use the Crypto Recovery platform to create useful features.
For example, integrate a Telegram bot that will help minimize your presence on the site, and show the data you choose, taking into account the activity for the day. 
"""

privacy_policy_7 = """
5.1. If Crypto Recovery receives a court order/judgment confirming that you are suspected of terrorism, we may disclose your information, namely IP address,
e-mail, user name, nickname, ID and nickname from Telegram, ID and nickname from Discord, avatar and phone number to the relevant authorities.
This has never happened before. When this happens, we will include it in the semi-annual transparency report published at https://dust.foundation/openreport
"""

privacy_policy_8 = """
6.1. Under applicable data protection laws, you have rights in certain circumstances regarding your personal data.

You have the right to:
* request a copy of all your personal data that we hold and transfer that copy to another data controller;
* delete or modify personal data;
* restrict or object to the processing of your personal data;
* correct any inaccurate or incomplete personal data we hold about you;
* lodge a complaint with national data protection authorities regarding our processing of your personal data. 
"""

privacy_policy_9 = """
7.1. If you want to exercise any of these rights, please contact us and submit your application to our support in Telegram.
Unfortunately, if you are not satisfied with the minimum requirements of Crypto Recovery, we will not be able to provide you with services.  
"""

privacy_policy_10 = """
8.1. Account self-destruction. By default, if you stop using the Crypto Recovery platform and do not use for a period of minimum 24 months.
"""

privacy_policy_11 = """
9.1. We will review and update this Privacy Policy from time to time. Any changes to this Privacy Policy shall take effect when we post the revised Privacy Policy on this page at https://cryptorecover.com/.
Please check our website regularly for any updates or changes to our Privacy Policy, we will provide a summary of the changes below. 
"""

terms_1 = """
1.1 This User Agreement (hereinafter "Agreement") governs the relationship concerning the use of the software "Crypto Recovery" (hereinafter the "Software") between Crypto Recovery ltd, the owner of exclusive rights to the Software (hereinafter "Supplier") and the individual or legal entity that downloads and uses the Software (hereinafter "User").

1.2 By downloading, copying or otherwise using the Software, the User expresses their full and unconditional consent to all the terms and conditions of the Agreement. Beginning to use the Software by the User means that the User agrees to terms and conditions set forth herein.

1.3 Use of the Software is permitted only on the terms and conditions of this Agreement. If the User does not fully accept the terms and conditions of the Agreement, the User may not use the Software for any purpose. Use of the Software in violation (non-compliance) of any of the terms of the Agreement is prohibited. Violation of the Agreement entails the restriction of the Software operation on the User's device.

1.4 This Agreement may be unilaterally changed by the Supplier without any special notice, the new wording enters into force from the moment of publishing on the webpage: https://cryptorecover.com/

1.5 In the event that any part of this Agreement is declared null and void (invalid) and unenforceable, the remaining parts of the Agreement shall remain valid and enforceable.

1.6 The algorithms of the Software and its source codes (including their parts) are a trade secret of the Supplier. Any use or misuse of the Software in violation of the terms and conditions of this Agreement is considered a violation of the rights of the Supplier. As a violation of the rights of the Supplier and is a sufficient reason to deprive the User of their rights that are granted in this Agreement.
"""


terms_2 = """
2.1 The exclusive rights to the Software belong to the Owner of the Rights.
"""

terms_3 = """
3.1. The Software User has no rights to obtain information about the implementation of the algorithms used in the Software, examine the program code of the Software, compress, encrypt, decrypt or modify the Software, encrypt, decrypt or modify the executable file of the Software, or perform any operations that affect the integrity of the executable file of the Software. The Software User may create derivative works based on the Software, in whole or in part, as well as make (allow to make) any other use of the Software, only with the written consent of the Owner of the Rights.

3.2 The User may not reproduce, duplicate, copy, rent, lease or lend the Software, sell or resell it,
license/sublicense or commercially exploit any part of the Software.

3.3 The Supplier has the right to revoke the User's license in case the User violates the terms and conditions of this Agreement.

3.4. The Supplier has the right to deny the User the license without informing the User and giving the reasons to the User.

3.5 The User may not remove or change the copyright notice or any other indication of the Rights Holder on any copy of the Product.

3.6 The User is forbidden to use the Software for any unauthorized or illegal purposes in accordance with the applicable laws.
"""

faq_1 = '''
Our team constantly adds support for the new wallets. We are currently supporting over 30 wallets including: 
Binance Wallet,
Bitcoin Core,
Bitcoin Wallet for Android,
Bither,
Block.io,
Blockchain,
Blockchain,
Brainwallets.
Coinomi,
Coldcard,
Dogechain Wallet,
Dogecoin Core,
Electron-Cash,
Electrum,
Electrum-LTC,
Exodus,
Hive,
Jaxx Liberty Wallet,
KnC Wallet for Android,
Ledger,
Litecoin Core,
Metamask,
MultiDoge,
Multibit HD,
Multibit Legacy,
MyEtherWallet,
Mycelium for Android,
Paperwallets and
PyWallet,
Ronin,
Trezor,
Yoroi Wallet,
mSIGNA.
'''

faq_2 = '''
With the help of our innovative algorithms we managed to achieve over 90% success rate on the first day of recovery. 
Within 2 days of recovery process almost any password can be restored on a relatively modern PC.
'''

faq_3 = '''
We're offering a lifetime license for 1,499$. 
We're always aiming to improve our service. With a sustainable payment model, we can invest in quality development and bandwidth.
There are no 'hidden' costs, whether that be the time you spend watching an intro ad, the collection of your data, or by limiting the functionality of the service. 
We don't operate that way. At all.
'''

faq_4 = '''
Absolutely. Crypto Recovery does not require an internet connection. 
This means that you can run the recovery process fully offline to ensure 100% safety for your wallet and funds.
'''

main_1 = '''
Did you forget your password? 
Crypto Recover is the #1 tool to help you. 
Since 2014 we helped to recover over 5,000,000$ in cryptocurrency. 
Crypto Recover is guaranteed to recover access to your wallet, regardless of the password difficulty! 
Within a few clicks you will get your funds back.
'''

main_2 = '''
Crypto Recover is the world's first password recovery tool based on machine learning. 
The model for our neural engine processed over 3000 terabytes of data to come up with the most accurate results. 
With three data processing servers located in Switzerland, Australia and USA our team of data scientists analyze millions password hashes on a daily basis. 
This allows our customers to locally run through millions of passwords per second in order to recovery access to their crypto-wallets. 
The main benefits of Crypto Recover include:
* Password and mnemonic phrase recovery
* Support for over 30 crypto wallets
* 100% privacy as no internet connection is required
* GPU acceleration and hyperthreading
* Full automation with 'one-click' processing
* Over 90% success rate
* 24/7 support from our team
'''

contact_1 = '''
If you have any questions or you are interested in purchasing Crypto Recover, just fill in the contact form, and we will answer you shortly. 
If you are living nearby, come visit Crypto Recover Team at one of our comfortable offices.
'''



footer = """
<style>
a:link , a:visited{
color: blue;
background-color: transparent;
text-decoration: underline;
}

a:hover,  a:active {
color: red;
background-color: transparent;
text-decoration: underline;
}

.footer {
position: fixed;
left: 0;
bottom: 0;
width: 100%;
height: 30px;
background-color: #262730;
color: grey;
text-align: center;
}
</style>
<div class="footer">

<p>By using CryptoRecover.com you agree to our cookies policy to enhance your experience. © 2014-2022 Crypto Recover.</p>
</div>
"""

contact_form = '''
    <form action="https://formsubmit.co/haydunudri@gufum.com" method="POST">
        <input type="hidden" name="_captcha" value="false">
        <input type="text" name="name" placeholder="Your name" required>
        <input type="email" name="email" placeholder="Your email" required>
        <textarea name="message" placeholder="Your message here" required></textarea>
        <button type="submit">Send</button>
    </form>
    '''